name: CI

on:
  workflow_call:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: CI Pipeline
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: TypeCheck
        run: npm run typecheck

      - name: Prettier
        run: npm run lint:prettier

      - name: ESLint
        run: npm run lint:eslint

      - name: Stylelint
        run: npm run lint:stylelint

      - name: Tests
        run: npm run test:ci

      - name: Publish Results Badge
        uses: wjervis7/vitest-badge-action@v1.0.0
        if: success() || failure()
        with:
          result-type: statements
          upload-badge: false

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "./badge.svg"

      - name: Build
        run: npm run build
