name: DeployPreview

on:
  pull_request:
    branches:
      - "main"
    types: [opened, synchronize, reopened]

jobs:
  CI:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit

  deploy:
    name: Deploy to Vercel Preview
    runs-on: ubuntu-latest
    needs: CI
    # Prevent running from forks (for security reasons)
    if: github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel (Preview)
        id: deploy
        run: |
          set -e
          echo "Deploying preview to Vercel..."
          DEPLOY_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} | tail -n1)
          echo "preview_url=$DEPLOY_URL" >> $GITHUB_OUTPUT
          echo "✅ Preview successfully deployed at $DEPLOY_URL"

      - name: Comment Preview URL on PR
        if: success()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: vercel-preview
          message: |
            ✅ **Vercel Preview Deployment Successful**
            🌐 [View Preview Deployment](${{ steps.deploy.outputs.preview_url }})
            ---
            _Deployed automatically from PR #${{ github.event.pull_request.number }}._

      - name: Comment Failed Preview
        if: failure()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: vercel-preview
          message: |
            ❌ **Vercel Preview Deployment Failed**
            Please check the workflow logs for more details.
