name: DeployProduction

on:
  push:
    branches:
      - "main"

jobs:
  CI:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit

  deploy:
    name: Deploy to Vercel Production
    runs-on: ubuntu-latest
    needs: CI

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
